VT02/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'', include('textEdit.urls', namespace='textEdit')),
    url(r'^users/', include('users.urls', namespace='users')),
]

textEdit/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^topics/$', views.topics, name='topics'),
    url(r'^topics/(?P<topic_id>\d+)/$', views.topic, name='topic'),
    url(r'^new_topic/$', views.new_topic, name='new_topic'),
    url(r'^new_entry/(?P<topic_id>\d+)/$', views.new_entry, name='new_entry'),
    url(r'^edit_entry/(?P<entry_id>\d+)/$', views.edit_entry, name='edit_entry'),
    url(r'^delete_topic/(?P<topic_id>\d+)/$', views.delete_topic, name='delete_topic'),
    url(r'^delete_entry/(?P<entry_id>\d+)/$', views.delete_entry, name='delete_entry'),
]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import login
from users import views

urlpatterns = [
    url(r'login/$', login, {'template_name': 'users/login.html'}, name='login'),
    url(r'^logout/$', views.logout_view, name="logout"),
    url(r'^register/$', views.register, name='register'),
]

textEdit/models.py
from django.db import models
from django.contrib.auth.models import User


class Topic(models.Model):
    """ Basic model for a Topic
    Return:
        title (str): The title of the topic.
    """
    title = models.CharField(max_length=100)
    # text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User)

    def __str__(self):
        return self.title


class Entry(models.Model):
    """ Basic model for an entry in a Topic
    Return:
        text(str): The text with a max length of 50
    """
    topic = models.ForeignKey(Topic)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        return self.text[:50] + '...'

users/models.py
from django.db import models

# Create your models here.

textEdit/forms.py
from django import forms
from .models import Topic, Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['title']
        labels = {'title': 'Title'}


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 80})}

textEdit/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.core.urlresolvers import reverse
from textEdit.models import Topic, Entry
from textEdit.forms import TopicForm, EntryForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate


def index(request):
    """ The index page of the web application
    :param request:
        Request made by the routing
    :return:
        Template: textEdit/index.html || The index page
    """
    return render(request, 'textEdit/index.html')


@login_required
def topics(request):
    """ The Topic page of the web application
    This is the overview of the topics.
    :param request:
    :return:
    """
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics': topics}
    return render(request, 'textEdit/topics.html', context)


def topic(request, topic_id):
    """ Overview of the topic selected
    :param request:
    :param topic_id:
        - id of the topic viewed
    :return:
        - request
        - template || /topic.html
        - context
    """
    topic = Topic.objects.get(id=topic_id)

    if topic.owner != request.user:
        raise Http404

    entries = topic.entry_set.order_by('-date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'textEdit/topic.html', context)


@login_required
def new_topic(request):
    """ Page for creating a new topic
    :param request:
    :return:
        - Request
        - redirect to new topic
        - context
    """
    if request.method != 'POST':
        form = TopicForm()
    else:
        form = TopicForm(data=request.POST)

        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('textEdit:topics'))
    context = {'form': form}
    return render(request, 'textEdit/new_topic.html', context)

@login_required
def new_entry(request, topic_id):
    """ Page for adding a entry to the selected topic
    :param request:
    :param topic_id:
        - Topic where an entry is being added
    :return:
        - redirects || dest = textEdit:topic
    """
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('textEdit:topic', args=[topic_id]))

    context = {'topic': topic, 'form': form}
    return render(request, 'textEdit/new_entry.html', context)


@login_required
def edit_entry(request, entry_id):
    """ A page where the entries can be changed (not deleted)
    :param request:
    :param entry_id:
    :return:
        - redirects || dest = textEdit:topic
    """
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic

    if request.method != 'POST':
        form = EntryForm(instance=entry)

    else:
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('textEdit:topic', args=[topic.id]))

    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'textEdit/edit_entry.html', context)


@login_required
def delete_topic(request, topic_id):
    """ deletes the topic selected
    :param request:
    :param topic_id:
    :return:
        - redirects || dest = textEdit:topics
    """
    topic = Topic.objects.get(id=topic_id)
    delete_topic = Topic.objects.get(pk=topic_id)

    if topic.owner != request.user:
        raise Http404
    else:
        delete_topic.delete()

    return HttpResponseRedirect(reverse('textEdit:topics'))


@login_required
def delete_entry(request, entry_id):
    entry = Entry.objects.get(id=entry_id)
    delete_entry = Entry.objects.get(id=entry_id)

    delete_entry.delete()

    return HttpResponseRedirect(reverse('textEdit:topics'))

# TO DO:
#     - page for deleting entries
#     - page for seeing someone else his/her entries on the topic
#     - page overview topics

users/views.py
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.contrib.auth import logout, login, authenticate
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('textEdit:index'))


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()

    else:
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username, password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('textEdit:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

textEdit/templates/textEdit/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>VT02</title>
    </head>
    <body>
        <h3>
            <a href="{% url 'textEdit:index' %}"> Index </a> -
            <a href="{% url 'textEdit:topics' %}"> Topics</a> -
            {% if user.is_authenticated %}
                Hello, {{ user.username }}. -
                <a href="{% url 'users:logout' %}">Log out</a>
            {% else %}
                <a href="{% url 'users:register' %}">Register</a> -
                <a href="{% url 'users:login' %}">Log in</a>
            {% endif %}
        </h3>
        {% block content %} {% endblock content %}
    </body>
</html>

textEdit/templates/textEdit/edit_entry.html
{% extends "textEdit/base.html" %}

{% block content%}

    <p>
        <a href="{% url 'textEdit:topic' topic.id %}">{{ topic }}</a>  -
    </p>

    <p>Edit entry</p>
    <form action="{% url 'textEdit:edit_entry' entry.id %}" method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">save changes</button>
    </form>

{% endblock content %}

textEdit/templates/textEdit/index.html
{% extends "textEdit/base.html" %}

{% block header %}
    <div class='jumbotron'>
        <h1>VT02</h1>
    </div>
{% endblock header %}

{% block content %}

    <p>
        <a href="{% url 'users:register' %}"> Register an account</a> to access
        everything on the website
    </p>
    <p>
        This will make sure that you can make new topics and make entries
    </p>

{% endblock content %}

textEdit/templates/textEdit/new_entry.html
{% extends "textEdit/base.html" %}

{% block content %}

    <p><a href="{% url 'textEdit:topic' topic.id %}">{{ topic }}</a> </p>
    <p>Add a new Entry: </p>
    <form action="{% url 'textEdit:new_entry' topic.id %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">add entry</button>
    </form>

{% endblock content %}

textEdit/templates/textEdit/new_topic.html
{% extends "textEdit/base.html" %}

{% block content %}
    <p>Add a new topic:</p>
    <form action="{% url 'textEdit:new_topic' %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">add topic</button>
    </form>
{% endblock content %}

textEdit/templates/textEdit/topic.html
{% extends 'textEdit/base.html' %}

{% block content %}

        <p>Topic: {{ topic }}</p>
    <p>Entries: </p>
    <div id="add/delete_entry v1">
        <p>
            <a href="{% url 'textEdit:new_entry' topic.id %}">add new entry</a> -
            <a href="{% url 'textEdit:delete_topic' topic.id %}">delete Topic</a>
        </p>
    </div>
    <ul>
        {% for entry in entries %}
            <li>
                <p>{{ entry.date_added|date:'d M, Y H:i' }} </p>
                <p>{{ entry.text|linebreaks  }}</p>
                <p>
                    <a href="{% url 'textEdit:edit_entry' entry.id %}">edit entry</a>
                </p>
            </li>
            {% empty %}
                <li>
                    There are no entries for this Topic yet.
                </li>
        {% endfor %}
    </ul>

{% endblock content %}

textEdit/templates/textEdit/topics.html
{% extends 'textEdit/base.html' %}
{% block content %}

    <h2>Topics</h2>
<ul>
    {% for topic in topics %}
    <li>
        <a href="{% url 'textEdit:topic' topic.id %}">{{ topic }}</a>
    </li>
    {% empty %}
    <li>No topics have been added yet</li>
    {% endfor %}
</ul>
<a href="{% url 'textEdit:new_topic' %}">Add a new Topic</a>
{% endblock content %}

users/templates/users/login.html
{% extends "textEdit/base.html" %}

{% block content %}

    {% if form.errors %}
        <p>Your username and password didn't match. Please try again.</p>
    {% endif %}

    <form method="post" action="{% url 'users:login' %}">
        {% csrf_token  %}
        {{ form.as_p }}
            <button name="submit">log in</button>
            <input type="hidden" name="next" value="{% url 'textEdit:index' %}" />
    </form>
{% endblock content %}

users/templates/users/register.html
{% extends "textEdit/base.html" %}

{% block content %}

    <form method="post" action="{% url 'users:register' %}">
        {% csrf_token %}
        {{ form.as_p }}

        <button name="submit">Register</button>
        <input type="hidden" name="next" value="{% url 'textEdit:index' %}" />
    </form>

{% endblock content %}